group = "com.example.eas_flutter_plugin"
version = "1.0"

buildscript {
    repositories {
        google()
        mavenCentral()
        maven {
            allowInsecureProtocol = true
            url "http://mvn.yifants.cn/artifactory/fineboost"
        }
    }

    dependencies {
        classpath("com.android.tools.build:gradle:8.7.0")
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            allowInsecureProtocol = true
            url "http://mvn.yifants.cn/artifactory/fineboost"
        }
    }
}

apply plugin: "com.android.library"

android {
    namespace = "com.example.eas_flutter_plugin"

    compileSdk = 35

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    defaultConfig {
        minSdk = 21
    }

    dependencies {
        implementation 'com.fineboost.sdk:dataacqu:5.0.55'
        implementation 'com.fineboost.sdk:utils:1.3.9'
        testImplementation("junit:junit:4.13.2")
        testImplementation("org.mockito:mockito-core:5.0.0")
    }

    testOptions {
        unitTests.all {
            testLogging {
               events "passed", "skipped", "failed", "standardOut", "standardError"
               outputs.upToDateWhen {false}
               showStandardStreams = true
            }
        }
    }
}
